### ISSUE TITLE
Batch sin interfaz Web al usuario

### ISSUE THREAD

**Issue by BaufestTeamNext** [BaufestTeamNext/SINE#1]
Se analizó el problema y el problema surgió debido a la falta de la librería jstl.jar en el directorio WEB-INF/lib.

**Comment by BaufestTeamNext** [comment]
Se creo el pasaje PSJ019483.

**Comment by ghost** [comment]
Aprobado el Pasaje para el día Lunes 26/01/2015.

**Comment by BaufestTeamNext** [comment]
El cliente verifico que funciona OK.
